/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Contenido;

import Funciones.GuardarArchivo;
import Grilla.ComponenteElectrico;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.Serializable;
import java.util.Map;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;



public class PruebaMatriz001 extends javax.swing.JFrame implements Printable, Serializable{

    /**
     * Creates new form PruebaMatriz001
     */
    Object datosComponentes[][];
    Object[] nombresComponentes = {"Elemento","Nombre"," I "," V "," P " };
    
    ButtonGroup grupoComponentes;
    private Contenido contentPane;
    
    Properties properties = new Properties();
    public PruebaMatriz001() {
        initComponents();
        grupoComponentes = new ButtonGroup();
        grupoComponentes.add(jtb_resistencia);
        grupoComponentes.add(jtb_extension);
        grupoComponentes.add(jtb_puntero);
        grupoComponentes.add(jtb_voltaje1);
        grupoComponentes.add(jtb_voltaje2);
        jTable1.setModel(new DefaultTableModel(datosComponentes, nombresComponentes));
        dialogTablaComponentes.setLocationRelativeTo(this);
        contentPane = new Contenido(this);
        jScrollPane1.setViewportView(contentPane);

    }
    
    public void setValores(ComponenteElectrico c){
        jl_nombreComponente.setText(c.getNom());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogTablaComponentes = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jtb_resistencia = new javax.swing.JToggleButton();
        jtb_extension = new javax.swing.JToggleButton();
        jtb_voltaje1 = new javax.swing.JToggleButton();
        jtb_voltaje2 = new javax.swing.JToggleButton();
        jtb_puntero = new javax.swing.JToggleButton();
        jtb_voltaje3 = new javax.swing.JToggleButton();
        jtb_voltaje4 = new javax.swing.JToggleButton();
        jtb_voltaje5 = new javax.swing.JToggleButton();
        jtb_voltaje6 = new javax.swing.JToggleButton();
        jtb_voltaje7 = new javax.swing.JToggleButton();
        jtb_voltaje8 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jl_nombreComponente = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jm_item_guardar = new javax.swing.JMenuItem();
        jm_item_imprimir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jm_item_mostrar_componentes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        dialogTablaComponentes.setTitle("Tabla de componentes");
        dialogTablaComponentes.setMinimumSize(new java.awt.Dimension(200, 200));
        dialogTablaComponentes.setSize(new java.awt.Dimension(500, 500));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout dialogTablaComponentesLayout = new javax.swing.GroupLayout(dialogTablaComponentes.getContentPane());
        dialogTablaComponentes.getContentPane().setLayout(dialogTablaComponentesLayout);
        dialogTablaComponentesLayout.setHorizontalGroup(
            dialogTablaComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTablaComponentesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogTablaComponentesLayout.setVerticalGroup(
            dialogTablaComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elena");
        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mallas eléctricas"));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Componentes"));

        jtb_resistencia.setBackground(new java.awt.Color(255, 255, 255));
        jtb_resistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/resistencia.jpg"))); // NOI18N
        jtb_resistencia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectResistencia(evt);
            }
        });

        jtb_extension.setBackground(new java.awt.Color(255, 255, 255));
        jtb_extension.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/extencion.jpg"))); // NOI18N
        jtb_extension.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectExtension(evt);
            }
        });

        jtb_voltaje1.setBackground(new java.awt.Color(255, 255, 255));
        jtb_voltaje1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/voltaje1.jpg"))); // NOI18N
        jtb_voltaje1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectVoltaje1(evt);
            }
        });

        jtb_voltaje2.setBackground(new java.awt.Color(255, 255, 255));
        jtb_voltaje2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/voltaje2.jpg"))); // NOI18N
        jtb_voltaje2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectVoltaje2(evt);
            }
        });

        jtb_puntero.setBackground(new java.awt.Color(255, 255, 255));
        jtb_puntero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/puntero.jpg"))); // NOI18N
        jtb_puntero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectPuntero(evt);
            }
        });

        jtb_voltaje3.setBackground(new java.awt.Color(255, 255, 255));
        jtb_voltaje3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/voltaje3.jpg"))); // NOI18N
        jtb_voltaje3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectVoltaje5(evt);
            }
        });

        jtb_voltaje4.setBackground(new java.awt.Color(255, 255, 255));
        jtb_voltaje4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/voltaje6.jpg"))); // NOI18N
        jtb_voltaje4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectVoltaje6(evt);
            }
        });

        jtb_voltaje5.setBackground(new java.awt.Color(255, 255, 255));
        jtb_voltaje5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/voltaje7.jpg"))); // NOI18N
        jtb_voltaje5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectVoltaje7(evt);
            }
        });

        jtb_voltaje6.setBackground(new java.awt.Color(255, 255, 255));
        jtb_voltaje6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/voltaje8.jpg"))); // NOI18N
        jtb_voltaje6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectVoltaje8(evt);
            }
        });

        jtb_voltaje7.setBackground(new java.awt.Color(255, 255, 255));
        jtb_voltaje7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/voltaje5.jpg"))); // NOI18N
        jtb_voltaje7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectVoltaje3(evt);
            }
        });

        jtb_voltaje8.setBackground(new java.awt.Color(255, 255, 255));
        jtb_voltaje8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/voltaje5.jpg"))); // NOI18N
        jtb_voltaje8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectVoltaje4(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtb_resistencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_voltaje1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtb_extension)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb_voltaje2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtb_voltaje7)
                    .addComponent(jtb_voltaje8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtb_voltaje3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb_voltaje5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtb_voltaje4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtb_voltaje6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(jtb_puntero)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtb_puntero))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtb_voltaje1)
                    .addComponent(jtb_voltaje3)
                    .addComponent(jtb_resistencia)
                    .addComponent(jtb_voltaje5)
                    .addComponent(jtb_voltaje7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtb_voltaje8)
                    .addComponent(jtb_voltaje2)
                    .addComponent(jtb_extension)
                    .addComponent(jtb_voltaje4)
                    .addComponent(jtb_voltaje6)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resolver"));

        jButton1.setText("Resolver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Seleccionar nodos");

        jButton3.setText("Mostrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jl_nombreComponente.setText("jLabel1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_nombreComponente)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_nombreComponente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel4);

        jMenu1.setText("Archivo");

        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jm_item_guardar.setText("Guardar");
        jm_item_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_item_guardarActionPerformed(evt);
            }
        });
        jMenu1.add(jm_item_guardar);

        jm_item_imprimir.setText("Imprimir");
        jm_item_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_item_imprimirActionPerformed(evt);
            }
        });
        jMenu1.add(jm_item_imprimir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Malla");

        jm_item_mostrar_componentes.setText("Mostrar tabala de componentes");
        jm_item_mostrar_componentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_item_mostrar_componentesActionPerformed(evt);
            }
        });
        jMenu2.add(jm_item_mostrar_componentes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Resolución");

        jMenuItem1.setText("Vaciar panel");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addComponent(jTabbedPane1)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selectResistencia(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectResistencia
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if(estado == evt.SELECTED){
            this.contentPane.setTipoComponente(11);
            
        }
        else
            this.contentPane.setTipoComponente(0);
    }//GEN-LAST:event_selectResistencia

    private void selectExtension(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectExtension
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if(estado == evt.SELECTED){
            this.contentPane.setTipoComponente(991);
        }
        else
            this.contentPane.setTipoComponente(0);
    }//GEN-LAST:event_selectExtension

    private void jm_item_mostrar_componentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_item_mostrar_componentesActionPerformed
        // TODO add your handling code here:
        this.datosComponentes = new Object[this.contentPane.map.size()][5];
        int i =0;
        for (Map.Entry<JLabel, ComponenteElectrico> lista : this.contentPane.map.entrySet()){  
            ComponenteElectrico c = lista.getValue();
            int x = c.getX();
            int y = c.getY();
            System.out.println("X: " + x + "; Y: " +y + "; Tipo: " + c.getTipo());
            System.out.println(i);
            this.datosComponentes[i][0] = c.getNom();
            this.datosComponentes[i][1] = c.getTipo();
            this.datosComponentes[i][2] = c.getVal();
            this.datosComponentes[i][3] = c.getTipo();
            
            i++;
        }
        jTable1.setModel(new DefaultTableModel(datosComponentes, nombresComponentes));
        
        dialogTablaComponentes.setVisible(true);
    }//GEN-LAST:event_jm_item_mostrar_componentesActionPerformed

    private void selectVoltaje1(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectVoltaje1
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if(estado == evt.SELECTED){
            this.contentPane.setTipoComponente(21);
        }
        else
            this.contentPane.setTipoComponente(0);
    }//GEN-LAST:event_selectVoltaje1

    private void selectPuntero(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectPuntero
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if(estado == evt.SELECTED){
            this.contentPane.setTipoComponente(0);
        }

    }//GEN-LAST:event_selectPuntero

    private void selectVoltaje2(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectVoltaje2
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if(estado == evt.SELECTED){
            this.contentPane.setTipoComponente(31);
        }
        else
            this.contentPane.setTipoComponente(0);
    }//GEN-LAST:event_selectVoltaje2

    private void selectVoltaje5(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectVoltaje5
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if(estado == evt.SELECTED){
            this.contentPane.setTipoComponente(61);
        }
        else
            this.contentPane.setTipoComponente(0);
    }//GEN-LAST:event_selectVoltaje5

    private void selectVoltaje6(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectVoltaje6
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if(estado == evt.SELECTED){
            this.contentPane.setTipoComponente(71);
        }
        else
            this.contentPane.setTipoComponente(0);
    }//GEN-LAST:event_selectVoltaje6

    private void selectVoltaje7(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectVoltaje7
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if(estado == evt.SELECTED){
            this.contentPane.setTipoComponente(81);
        }
        else
            this.contentPane.setTipoComponente(0);
    }//GEN-LAST:event_selectVoltaje7

    private void selectVoltaje8(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectVoltaje8
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if(estado == evt.SELECTED){
            this.contentPane.setTipoComponente(91);
        }
        else
            this.contentPane.setTipoComponente(0);
    }//GEN-LAST:event_selectVoltaje8

    private void selectVoltaje3(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectVoltaje3
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if(estado == evt.SELECTED){
            this.contentPane.setTipoComponente(41);
        }
        else
            this.contentPane.setTipoComponente(0);
    }//GEN-LAST:event_selectVoltaje3

    private void selectVoltaje4(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectVoltaje4
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if(estado == evt.SELECTED){
            this.contentPane.setTipoComponente(41);
        }
        else
            this.contentPane.setTipoComponente(0);
    }//GEN-LAST:event_selectVoltaje4
   

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.contentPane.setTipoComponente(1);
        int c = Integer.valueOf(JOptionPane.showInputDialog("Número de nodos:"));    
        this.contentPane.setCantNodos(c);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jm_item_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_item_guardarActionPerformed
        
        JFileChooser jfcs = new JFileChooser();        
        //jfcs.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfcs.addChoosableFileFilter(new FileNameExtensionFilter("Archivos del sistema", "ele"));
        jfcs.setAcceptAllFileFilterUsed(true);
        int option = jfcs.showSaveDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {
            String ruta = jfcs.getSelectedFile().getPath()  + ".ele";
            GuardarArchivo ga = new GuardarArchivo(ruta, contentPane.map);
            ga.escribir();
        }
        
        
    }//GEN-LAST:event_jm_item_guardarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        contentPane.vaciarPanel();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jm_item_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_item_imprimirActionPerformed
        // TODO add your handling code here:
        try {
            // Open printer dialog and pass JPanel to print
                PrinterJob job = PrinterJob.getPrinterJob();
                job.setPrintable(this);
               
                if(job.printDialog()) job.print();
                
        } catch (PrinterException ex) {
            Logger.getLogger(PruebaMatriz001.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jm_item_imprimirActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfco = new JFileChooser();
        //jfco.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfco.addChoosableFileFilter(new FileNameExtensionFilter("Archivos del sistema", "ele"));
        jfco.setAcceptAllFileFilterUsed(true);
        int option = jfco.showOpenDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {
            String filename = jfco.getSelectedFile().getPath();
            System.out.println(filename);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaMatriz001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaMatriz001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaMatriz001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaMatriz001.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaMatriz001().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dialogTablaComponentes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jl_nombreComponente;
    private javax.swing.JMenuItem jm_item_guardar;
    private javax.swing.JMenuItem jm_item_imprimir;
    private javax.swing.JMenuItem jm_item_mostrar_componentes;
    private javax.swing.JToggleButton jtb_extension;
    private javax.swing.JToggleButton jtb_puntero;
    private javax.swing.JToggleButton jtb_resistencia;
    private javax.swing.JToggleButton jtb_voltaje1;
    private javax.swing.JToggleButton jtb_voltaje2;
    private javax.swing.JToggleButton jtb_voltaje3;
    private javax.swing.JToggleButton jtb_voltaje4;
    private javax.swing.JToggleButton jtb_voltaje5;
    private javax.swing.JToggleButton jtb_voltaje6;
    private javax.swing.JToggleButton jtb_voltaje7;
    private javax.swing.JToggleButton jtb_voltaje8;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex > 0) { /* We have only one page, and 'page' is zero-based */
            return NO_SUCH_PAGE;
        }

        Graphics2D g2d = (Graphics2D)graphics;
        g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

        contentPane.printAll(graphics);
        

        return PAGE_EXISTS;
    }
}
